name: Auto-merge Dependabot
on: pull_request
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          approve: true
          merge-method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

