name: Auto-merge Dependabot

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # Merge patch/minor updates automatically; major left for manual review
          target: minor
          approve: true
          merge-method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}