name: Release Guard

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-release-readiness:
    name: Verify tag/version/changelog & workflow sanity
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag
        id: tag
        shell: bash
        run: |
          set -euo pipefail
          tag="${GITHUB_REF#refs/tags/}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"

      - name: Ensure VERSION matches tag (no leading v)
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f VERSION ]]; then
            echo "VERSION file missing" >&2; exit 1
          fi
          tag="${{ steps.tag.outputs.tag }}"
          if [[ "$(cat VERSION)" != "${tag#v}" ]]; then
            echo "VERSION '$(cat VERSION)' does not match tag '${tag}'" >&2
            exit 1
          fi

      - name: Ensure CHANGELOG references tag
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ steps.tag.outputs.tag }}"
          if ! grep -Eq "^##?\\s*(${tag}|${tag#v})\\b" CHANGELOG.md; then
            echo "CHANGELOG.md missing section for ${tag}" >&2
            exit 1
          fi

      - name: actionlint (workflows sanity)
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -color=never