name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes with git-cliff
        id: cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: .git-cliff.toml
          args: --tag ${{ github.ref_name }}
        env:
          OUTPUT: CHANGELOG_GENERATED.md

      - name: Create archive and checksum
        id: archive
        shell: bash
        run: |
          set -euo pipefail
          tag="${GITHUB_REF_NAME}"
          name="bash_setup-${tag}"
          mkdir -p dist
          tar czf "dist/${name}.tar.gz" --exclude .git --exclude .github .
          (cd dist && sha256sum "${name}.tar.gz" | awk '{print $1}' > "${name}.tar.gz.sha256")
          echo "archive=dist/${name}.tar.gz" >> "$GITHUB_OUTPUT"
          echo "checksum=dist/${name}.tar.gz.sha256" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: CHANGELOG_GENERATED.md
          files: |
            ${{ steps.archive.outputs.archive }}
            ${{ steps.archive.outputs.checksum }}